# Generated by Django 4.2.7 on 2023-11-14 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('required_caregiving_type', models.CharField(max_length=50)),
                ('other_requirements', models.TextField()),
                ('date_posted', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('given_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('profile_description', models.TextField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('member_user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.user')),
                ('house_number', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('caregiver_user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.user')),
                ('photo', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('caregiving_type', models.CharField(max_length=50)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.user')),
                ('house_rules', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField()),
                ('caregiver_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='member_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('work_hours', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('caregiver_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_caregiver', to='main.user')),
                ('member_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_member', to='main.user')),
            ],
        ),
    ]
