# Generated by Django 4.2.7 on 2023-11-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobApplication',
            new_name='Job_Application',
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='photo',
            field=models.ImageField(default='blank_profile_image.jpg', upload_to='profile_images'),
        ),
    ]
