# Generated by Django 4.2.7 on 2023-11-14 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_jobapplication_job_application_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='caregiver_user_id',
            new_name='caregiver_user',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='member_user_id',
            new_name='member_user',
        ),
        migrations.RenameField(
            model_name='caregiver',
            old_name='caregiver_user_id',
            new_name='caregiver_user',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='member_user_id',
            new_name='member_user',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='caregiver_user_id',
            new_name='caregiver_user',
        ),
        migrations.RenameField(
            model_name='job_application',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_user_id',
            new_name='member_user',
        ),
    ]
