# Generated by Django 4.2.7 on 2023-11-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_caregiver_user_id_appointment_caregiver_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='house_rules',
            field=models.TextField(null=True),
        ),
    ]
