# Generated by Django 4.2.7 on 2023-11-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_member_house_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='photo',
            field=models.ImageField(default='blank_profile_image.jpg', null=True, upload_to='profile_images'),
        ),
    ]
