# Generated by Django 4.2.7 on 2023-11-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_caregiver_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='member_user_id',
            new_name='member_user',
        ),
    ]
