# Generated by Django 4.2.7 on 2023-11-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
