# Generated by Django 4.2.7 on 2023-11-20 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_user_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='job_application',
            name='date_applied',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
